version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker_images/curler
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker_images/java7
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker_images/java8
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker_images/marshalsec
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker_images/nginx
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker_images/reverse_shell
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /marshalsec
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /poc_template
    schedule:
      interval: daily
