version: '3.4'

services:

  curl_attacker:
    image: curler
    depends_on:
      - spring-boot-app
      - marshalsec
      - exploit-http-server
    environment:
      PAYLOAD: "${PAYLOAD}"
    volumes:
      - ${PWD}/exploits.sh:/exploits.sh
    extra_hosts:
      host.docker.internal: host-gateway

  marshalsec:
    image: marshalsec
    expose:
      - "1389"
    ports:
      - "1389:1389"
    extra_hosts:
      host.docker.internal: host-gateway

  spring-boot-app:
    image: poc:${JAVA_VERSION}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      LOG4J_VERSION: ${LOG4J_VERSION}
    extra_hosts:
      host.docker.internal: host-gateway

  exploit-http-server:
    image: exploit_nginx
    expose:
      - "80"
    ports:
      - "8888:80"
    extra_hosts:
      host.docker.internal: host-gateway
