version: '3.4'

services:

  curl_attacker:
    image: curler
    networks:
      - the_internet
    depends_on:
      - sprint-boot-app
      - marshalsec
      - exploit-http-server
    environment:
      PAYLOAD: "${PAYLOAD}"
    volumes:
      - ${PWD}/exploits.sh:/exploits.sh

  marshalsec:
    image: marshalsec
    networks:
      - the_internet
    expose:
      - "1389"

  sprint-boot-app:
    image: poc:${JAVA_VERSION}
    networks:
      - the_internet
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      LOG4J_VERSION: ${LOG4J_VERSION}

  exploit-http-server:
    image: exploit_nginx
    networks:
      - the_internet
    expose:
      - "80"
    ports:
      - "8888:80"

networks:
  the_internet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
