name: Extended test

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:  
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Build the images
        run: |
          ./build_images.sh

      - name: Test the exploit lab using the python cli (java8) [Non vulnerable]
        run: |
          python log4shell-validator.py  --java-version 8 --log4j-version 2.12.2 --debug | tee 8_2.12.2.txt
          grep "vulnerable to CVE-2021-44228" 8_2.12.2.txt

      - name: Test the exploit lab using the python cli (java8) [Non vulnerable]
        run: |
          python log4shell-validator.py  --java-version 8 --log4j-version 2.15.0 --debug | tee 8_2.15.0.txt
          grep "vulnerable to CVE-2021-44228" 8_2.15.0.txt

      - name: Test the exploit lab using the python cli (java8) [vulnerable]
        run: |
          python log4shell-validator.py  --java-version 8 --log4j-version 2.12.1 --debug | tee 8_2.12.1.txt
          grep "not vulnerable to CVE-2021-44228" 8_2.12.1.txt
        
      - name: Test the exploit lab using the python cli (java8) [vulnerable]
        run: |
          python log4shell-validator.py  --java-version 8 --log4j-version 2.14.0 --debug | tee 8_2.14.0.txt
          grep "not vulnerable to CVE-2021-44228" 8_2.14.0.txt
        