name: Basic test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the images
        run: |
          ls -artl
          ./build_images.sh
          
      - name: Simulate the attack
        run: python cli.py --java-version java --log4j-version 2.12.1 