name: Basic test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:  
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Build the images
        run: |
          ./build_images.sh
          
      - name: Run the exploit lab using the bash script
        run: |
          ./run_containers.sh
          ./delete_containers.sh

      - name: The the exploit lab using the python cli (java7)
        run: |
          python log4shell-validator.py  --java-version 8 --log4j-version 2.12.1
          python log4shell-validator.py  --java-version 8 --log4j-version 2.12.2
